trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  
steps:
- script: dotnet restore
  displayName: 'dotnet restore'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    outputDir: '$(Build.ArtifactStagingDirectory)/TestDir'
